Repository ansible-collections/community.network, pull requests merged in 2020-11, with the labels that each got.

#138 Update routeros.py
  changelogs/fragments/138-routeros-allow-slash.yml
  plugins/terminal/routeros.py
Labels: backport-1

#151 Fix and deprecate fortimanager httpapi plugin
  changelogs/fragments/fortimanager-imports.yml
  plugins/httpapi/fortimanager.py
Labels: affects_2.10, backport-1, bug, community_review, httpapi, plugins

#129 Change vendored ipaddress import to regular import
  changelogs/fragments/netcommon_ipaddress.yaml
  plugins/modules/network/cnos/cnos_static_route.py
Labels: breaking_change

#159 Fixed action plugins import non-existing module from ansible.netcommon issue
  plugins/action/aireos.py
  plugins/action/aruba.py
  plugins/action/ce.py
  plugins/action/cnos.py
  plugins/action/enos.py
  plugins/action/ironware.py
  plugins/action/sros.py
Labels: backport-1

#173 Fix boolean defaults.
  plugins/doc_fragments/avi.py
  plugins/modules/network/avi/avi_useraccount.py
  plugins/modules/network/cloudengine/ce_multicast_igmp_enable.py
  plugins/modules/network/icx/icx_banner.py
  plugins/modules/network/icx/icx_interface.py
  plugins/modules/network/icx/icx_user.py
  plugins/modules/network/ingate/ig_config.py
  plugins/modules/network/nso/nso_action.py
  plugins/modules/network/panos/panos_security_rule.py
  plugins/modules/network/routeros/routeros_api.py
  plugins/modules/network/slxos/slxos_linkagg.py
Labels: backport-1

#174 [stable-1] Add information on routeros content migration
  changelogs/fragments/routeros-migration.yml
Labels: affects_2.10, community_review, docs, has_issue, needs_triage, owner_pr

#175 Remove deprecated redirects for 2.0.0
  changelogs/fragments/remove-deprecated-redirects.yml
  meta/runtime.yml
Labels: affects_2.10, breaking_change, bug, community_review

#181 Improve routeros migration
  changelogs/fragments/101_update_routeros_facts.yml
  changelogs/fragments/104_routeros_facts_export_verbose.yml
  changelogs/fragments/138-routeros-allow-slash.yml
  changelogs/fragments/routeros-3-api-ssl.yml
  changelogs/fragments/routeros-migration-removal.yml
Labels: breaking_change

#179 Bump version to 2.0.0
  galaxy.yml
Labels: breaking_change
