Repository ansible-collections/community.network, pull requests merged in 2021-04, with the labels that each got.

#236 Add 2.11 to tests
  .azure-pipelines/azure-pipelines.yml
Labels: backport-1, backport-2

#239 trying page_size patch
  tests/utils/shippable/collection_versions_page_size.patch
  tests/utils/shippable/shippable.sh
Labels: affects_2.10, community_review, needs_triage

#240 Drop support of testing against devel branch in stable-1 branch
  .azure-pipelines/azure-pipelines.yml
  shippable.yml
Labels: affects_2.10, community_review, feature, needs_triage

#244 added page_size patches for multiple ansible versions
  tests/utils/shippable/collection_versions_page_size-2.10.patch
  tests/utils/shippable/collection_versions_page_size-2.11.patch
  tests/utils/shippable/collection_versions_page_size-2.9.patch
  tests/utils/shippable/collection_versions_page_size-devel.patch
  tests/utils/shippable/shippable.sh
Labels: backport-1, backport-2

#252 temporarily disabling some (3) unit tests
  tests/unit/plugins/modules/network/exos/test_exos_config.py.disabled
  tests/unit/plugins/modules/network/icx/test_icx_config.py.disabled
  tests/unit/plugins/modules/network/voss/test_voss_config.py.disabled
Labels: backport-2

#256 BOTMETA.yml - add team_edgeos, add new maintainers
  .github/BOTMETA.yml
Labels: backport-1, backport-2
