Repository ansible-collections/community.network, pull requests merged in 2021-11, with the labels that each got.

#314 Fix ce_switchport module with connection type ansible.netcommon.netconf
  changelogs/fragments/313_fix_broken_ce_switchport_module.yaml
  plugins/modules/network/cloudengine/ce_switchport.py
Labels: bug, needs_ci, new_contributor, module, plugins, small_patch

#189 feat(edgeos_config): Append save command into result
  changelogs/fragments/189-append-save-command-into-result.yaml
  plugins/modules/network/edgeos/edgeos_config.py
Labels: needs_ci, new_contributor, feature, module, plugins, small_patch, community_review, needs_triage, affects_2

#331 removed unnecessary requirement
  tests/unit/requirements.txt
Labels: backport-2, backport-3

#334 removed unnecessary FortiOS requirements
  tests/unit/requirements.txt
  tests/utils/constraints.txt
  tests/utils/requirements.txt
Labels: backport-2, backport-3

#337 updated the README example for 'community.network.a10_server'
  README.md
Labels: needs_ci, docs, backport-2, backport-3
